# Generated by Django 4.2.1 on 2023-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_address_alter_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('update_desc', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('phoneNo', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=50)),
            ],
        ),
    ]
